services:
  db:
    image: mariadb:latest
    container_name: container_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web:
    image: httpd:latest
    container_name: container_apache
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: testdb
    networks:
      - docker-network
    depends_on:
      - db

networks:
  docker-network:
    driver: bridge